name: TPP-MLIR Base Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  TPP-MLIR-gcc-rel:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: GCC Release
        run: |-
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"

  TPP-MLIR-gcc-deb:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: GCC Debug
        run: |-
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"

  TPP-MLIR-clang-rel:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Clang Release
        run: |-
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"

  TPP-MLIR-clang-deb:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Clang Debug Sanitizers
        run: |-
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"
