name: TPP-MLIR Base Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  TPP-MLIR-base-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Base Test
        run: |-
          echo "Event Name: ${{ github.event_name }}"
          if [ ${{ github.event_name }} == "pull_request" ]; then
            echo "Event Label: ${{ github.event.label.name }}"
            echo "PR Labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"
          fi
          if [ ${{ github.event_name }} == "workflow_dispatch" ]; then
            echo "RUN_EMR_BENCH: ${{ inputs.RUN_EMR_BENCH }}"
          fi
